### ISSUE TITLE
Add dust.exists() function to see if template has been cached (w/ implementation)

### ISSUE THREAD

**Issue by jbcpollak** [linkedin/dustjs#209]
I have added this function to my branch of dust, I use to to know if a template exists before I call render():

dust.exists = function(name) {
    var tmpl = dust.cache[name];
    if (tmpl) {
        return true;
    } else {
        return false; 
    }
};

Perhaps this isn't necessary in most cases, I have been using dust through Rhino and it seemed like the best solution at the time. Anyway, it seems like a useful function to have.

**Comment by tonytopper** [comment]
This could be very useful for dynamically named template files.

**Comment by sethkinast** [comment]
This logic should likely be part of your `dust.onLoad` hook.

**Comment by soldiercnorm** [comment]
This would be nice

**Comment by dehimer** [comment]
My use case: check invoice template depending on the current user language.
Show button of invoice if exist template for current language.
I use nodejs and now I decide it by testing existing template file by name "invoicehtml<lang>.dust".
Don't beautiful. I except something like this: dust.check("invoicehtml"+lang)
