### ISSUE TITLE
Support negative ints in the grammar rules for consistency

### ISSUE THREAD

**Issue by vybs** [linkedin/dustjs#276]
number "number"
  = n:(float / integer) { return ['literal', n]; }

float "float"
  = l:integer "." r:integer+ { return parseFloat(l + "." + r.join('')); }

integer "integer"
  = digits:[0-9]+ { return parseInt(digits.join(""), 10); }

**Comment by sethkinast** [comment]
Eek how has this gone unsupported for so long

**Comment by prashn64** [comment]
@jasonbelmonti can you look at this issue?

**Comment by sethkinast** [comment]
Closed by #550
