### ISSUE TITLE
User templates can no longer get templateName

### ISSUE THREAD

**Issue by rragan** [linkedin/dustjs#385]
I’m updating the Wiki to cover 2.2.x versions. At 2.0.x we added {_templateName_} to global and then moved it to context. Now that seems to be gone. I guess this is a backward incompatible change. I see the getTemplateName method on Context but how might a user template wanting to display the template name do this now without dropping down into JS?

**Comment by sethkinast** [comment]
Since you can get the template name in context and we've established that if we add something it will be a helper, closing this out.
