### ISSUE TITLE
Dust does not propagate thrown errors from a helper if async onLoad is used

### ISSUE THREAD

**Issue by ghost** [linkedin/dustjs#481]
Recently error propagation was fixed for most asynchronous cases (see https://github.com/linkedin/dustjs/pull/471). However, this still leaves open the possibility of losing failures in onLoad. The following is a copy of details from https://github.com/linkedin/dustjs/pull/471#issuecomment-45240212.

Here's an example:

``` html
<!doctype html>

<script src="dust-full.js"></script>
<script>
  dust.onLoad = function(name, callback) {
    dust.nextTick(function() {
      switch (name) {
        case 'bad': callback(null, "BEFORE_BAD {@bad/} AFTER_BAD"); break;
        default: callback('No such template!'); break;
      }
    });
  };

  dust.helpers.bad = function() {
    throw new Error("Ooops!");
  };

  var stream;
  try {
    stream = dust.stream("bad", {});
  } catch (e) {
    console.log("DUST STREAM THREW", e);
  }

  stream.on("data", function(data) {
    console.log("STREAM DATA", data);
  });
  stream.on("error", function(err) {
    console.log("STREAM ERROR", err);
  });
  stream.on("end", function() {
    console.log("STREAM END");
  });
</script>
```

The chrome console shows an empty chunk followed by an uncaught error:

```
STREAM DATA  index.html:26
Uncaught Error: Ooops! index.html:15
dust.helpers.bad index.html:15
Chunk.helper dust-full.js:787
body_0 VM335:1
(anonymous function) dust-full.js:156
(anonymous function)
```

For now we have disabled onLoad for our use cases, but we'd like to re-enable it once it is safe.

**Comment by edobry** [comment]
Is there anything I need to enable to make this work? I'm using v2.6.2 and errors are still being swallowed.

**Comment by sethkinast** [comment]
Could you provide an example of your code that results in no error?

**Comment by edobry** [comment]
Not at the moment, it's all tangled up with other code. I tried both `dust.debugLevel = "DEBUG"` and `dust.isDebug = true` and neither seemed to help. Is there something obvious I'm missing maybe?
