### ISSUE TITLE
Dust doesn't render a result set obtained from MongoDB (by Mongoose)

### ISSUE THREAD

**Issue by wzup** [linkedin/dustjs#487]
I have an issue: Dust doesn't render a result set from MongoDB by Mongoose. But a custom made array of objects renders just fine. What is wrong? Why it happens? How to manage it? I use Windows 7 64bit if it matters.

Here is a code.

This is my controller. Pay attention to two `model` objects. The first one (custom made) is 
rendered fine. The second one (obtained from MongoDB) is not rendered.

```
    router.get('/', function (req, res) {

        Post.find(function (err, posts) {
            if (err) {
                console.log(err);
            }

            //
            // This is rendered just fine
            //
            var model = {
                posts: [
                    {title: "Title1", body: "Body1"},
                    {title: "Title2", body: "Body2"}
                ]
            };

            //
            // This model is not rendered by Dust
            //
            var model = {
                posts: posts
            }

            res.render('posts', model);
        });
    });
```

A result set from MongoDB that is not rendered. Its Schema:

```
    var postSchema = mongoose.Schema({
        title: String,
        body: String,
        crAt: { type: Date, default: Date.now },
        upAt: { type: Date, default: Date.now }
    });
```

My `.dust` template code:

```
{>"layouts/master" /}
{<title}
    Posts
{/title}

{<body}
    {>"partials/header" /}
    <div id="container" class="container">

    <ul>
    {#posts}
        <li>
            {.title}
            <br>
            {.body}
        </li>
    {/posts}
    </ul>

        {>"partials/footer" /}
    </div>
{/body}
```

**Comment by vanmartin** [comment]
I'm unsure whether to create a new issue or simply comment on this one. Seeing as it contains some useful history on the issue, I'll post my comment here.

I've just upgraded to version 2.7.1 and I've noticed that a Passportjs object retrieved from MongoDB causes my page to hang (no issues before the upgrade though). Wrapping it with the JSON.parse & JSON.stringify functions as follows does however seems to sort out the issue:

```javascript
        res.render('casestudies', {
            user : JSON.parse(JSON.stringify(req.user)), 
            assessments : req.assessments
        });
```

What I find really strange is the same is not necessary for req.assessments with also happens to be retrieved from MongoDB.

This is what my User model looks like:

```javascript
var userSchema = mongoose.Schema({
    local            : {
        name         : String,
        email        : String,
        password     : String,
    },
    userRoles : [Number]
});
```

My apologies in advance if I'm doing something daft without realising it.

**Comment by sethkinast** [comment]
Does either `dust.isThenable` or `dust.isStreamable` return true if you pass it the object? Sounds like duck typing that I can fix.

**Comment by sethkinast** [comment]
If so, can you share the versions of mongoose and mongodb you're using?

**Comment by sethkinast** [comment]
I tried briefly to repro but I'm sure I'm only scratching the surface. It does seem that Dust is rendering the object returned by a `find`, at least.

```
var mongoose = require('mongoose');
var dust = require('dustjs-linkedin');

mongoose.connect('mongodb://localhost/test');

var Cat = mongoose.model('Cat', { name: String });

var kitty = new Cat({ name: 'Zildjian' });
kitty.save(function (err) {
  console.log('meow');

  Cat.find(function(err, data) {
    console.log(data);

    dust.renderSource("Kittens: {#kittens}{name}{~n}{/kittens}", {
      kittens: data
    }, function(err, out) {
      console.log(out);
    });
  });
});
```
After running a couple times:
```
$ node app.js
meow
[ { _id: 55538a05ccd52aa66dbbd79d, name: 'Zildjian', __v: 0 },
  { _id: 55538a105d5791a76d45461b, name: 'Zildjian', __v: 0 },
  { _id: 55538a2010a650aa6d408075, name: 'Zildjian', __v: 0 } ]
Kittens: Zildjian
Zildjian
Zildjian
```

**Comment by sethkinast** [comment]
It looks like mongo Documents are Streamables, so my guess is that they aren't being `end`ed or are ALREADY `end`ed. Once you come back with more info we'll be able to narrow this down.

**Comment by vanmartin** [comment]
> Does either dust.isThenable or dust.isStreamable return true if you pass it the req.user object? Sounds like duck typing that I can fix.

**dust.isThenable** return **false** 
**dust.isStreamable** return **true**

> If so, can you share the versions of mongoose and mongodb you're using?
 
Mongoose: **3.8.28**
MongoDB: **2.6.7**

> I tried briefly to repro but I'm sure I'm only scratching the surface.

I can confirm that we managed to reproduce the error on another dev's machine as well.

Please let me know if you need more info. Happy to help get this resolved although I can confirm that everything plays nicely when reverting back to dust **2.6.2**

**Comment by sethkinast** [comment]
Thanks, I was able to reproduce it.

So Documents in Mongo can be asynchronously delivered, but I don't think
they conform to the normal Streams API. I'm going to dig into how to best
support them in Dust, whether that means submitting a patch to upstream or
being pickier about what Dust thinks a stream is.

If you want to work around it for now, address Mongo Documents as
references, not as sections.

So instead of:

    {#req.user}{name}{/req.user}

Use:

    {req.user.name}

Dust 2.7.0 added Streamable support which is why you don't see it before
then.

Thanks for the report! We'll get this behavior improved as soon as we can.

On Thu, May 14, 2015 at 5:02 AM, vanmartin <notifications@github.com> wrote:

> Does either dust.isThenable or dust.isStreamable return true if you pass
> it the req.user object? Sounds like duck typing that I can fix.
>
> *dust.isThenable* return *false*
> *dust.isStreamable* return *true*
>
> If so, can you share the versions of mongoose and mongodb you're using?
>
> Mongoose: *3.8.28*
> MongoDB: *2.6.7*
>
> I tried briefly to repro but I'm sure I'm only scratching the surface.
>
> I can confirm that we managed to reproduce the error on another dev's
> machine as well.
>
> Please let me know if you need more info. Happy to help get this resolved
> although I can confirm that everything plays nicely when reverting back to
> dust *2.6.2*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkedin/dustjs/issues/487#issuecomment-102012952>.
>



-- 
Seth Kinast
http://sethkinast.com/

**Comment by vanmartin** [comment]
Thanks! I managed to work out that it breaks on sections but not references by a process of elimination  earlier in the week but honestly there's no immediate pressing need for me to upgrade my Dust version. Reverting back to 2.6.2 is my best option at the moment as I use sections in quite a number of my existing templates. 

I'll keep following the conversation on issue #663.
