### ISSUE TITLE
Is there any way to iterate on Objects? for..in loop functionality

### ISSUE THREAD

**Issue by matenadasdi** [linkedin/dustjs#491]
I think its a mandatory to be able to iterate on objects, and also to get the current key.

Is there a way for this already?

**Comment by jpray** [comment]
Handlebars does it. https://github.com/wycats/handlebars.js/blob/9589ab89492c23e1d201f61617ae2a3bf54a0afc/lib/handlebars/base.js#L80-L86

I think Dust should support this also.  It's useful.

**Comment by sethkinast** [comment]
It's quite easy to write a helper to extend Dust if you'd like to add this
functionality to your codebase. If you don't need the special features of
@rragan's iterate helper, you can write one that's basically `for var in
obj` in about four lines of code.

On Fri, Mar 27, 2015 at 10:42 PM, jpray <notifications@github.com> wrote:

> Handlebars does it.
> https://github.com/wycats/handlebars.js/blob/9589ab89492c23e1d201f61617ae2a3bf54a0afc/lib/handlebars/base.js#L80-L86
>
> I think Dust should support this also. It's useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkedin/dustjs/issues/491#issuecomment-87165784>.
>



-- 
Seth Kinast
http://sethkinast.com/
