### ISSUE TITLE
Inject code into server-rendered dust templates?

### ISSUE THREAD

**Issue by kevinSuttle** [linkedin/dustjs#523]
https://gist.github.com/kevinSuttle/c8b198aaa30349088c35#comment-1341611

**Comment by sethkinast** [comment]
From the comment on your Gist, [you appear to be using the wrong `proxy` option.](https://gist.github.com/kevinSuttle/c8b198aaa30349088c35#comment-1387860) Dust doesn't care what you do with the string after it's been rendered. The proxy is just running a string replace for </body> or something and adding its script tag.
