### ISSUE TITLE
Default dust.debugLevel should not be NONE

### ISSUE THREAD

**Issue by rragan** [linkedin/dustjs#524]
The  dust.debugLevel = NONE; seems to be recipe for headaches. I can't recall the reasons for not setting this to at least WARN. Several times now, this has cost folks some hours chasing down the cause of a problem that would have been found quickly

**Comment by sethkinast** [comment]
How about looking for DEBUG=dust in the way that `request`, `express

**Comment by sethkinast** [comment]
`request

**Comment by rragan** [comment]
Seems like a good idea but my notes say NODE_DEBUG=express:* is what you use. Or do they also support DEBUG...    NODE_DEBUG would seem wrong in a client settting.

**Comment by sethkinast** [comment]
Really brief look makes it seem that NODE_DEBUG is for Node internals stuff: http://www.juliengilli.com/2013/05/26/Using-Node.js-NODE_DEBUG-for-fun-and-profit/

and DEBUG is supported by stuff that uses https://github.com/visionmedia/debug

**Comment by rragan** [comment]
Ah, could well be. Having a greater interest in the internals, I tend to use the former. DEBUG would work for both. I assume it sets the debuglevel to debug?

**Comment by sethkinast** [comment]
In a client setting I think you would just set `dust.debugLevel`, I'm not sure we can detect a development environment for a browser.

Does this sound legit? I am really just spitballing because I want to drive this issue instead of letting it languish.

Is there a better approach?

**Comment by rragan** [comment]
Since I raised the issue, DEBUG=dust would help (can DEBUG stack multiple things, e.g. DEBUG=DUST:EXPRESS:... so we would need to do a slightly more elaborate check. This would make it easier for developers to turn on more checking but in our usages, it seems like a lot of warnings get swallowed and if things just sort of work, no one notices until too late. But I can force the setting in our infrastructure to be at least WARN.

**Comment by sethkinast** [comment]
DEBUG=dust,express,foobar is the standard (easy to regex)

That also allows things like DEBUG=dust:compile (only turn on debugger for compiler, if we wanted to namespace logging someday).

That would at least allow you to turn on debugging without needing a reference to Dust.

**Comment by rragan** [comment]
Or perhaps DEBUG=dust:warn

**Comment by sethkinast** [comment]
Yep, we could use the namespacing to allow you to set a level.
