### ISSUE TITLE
'util.print: use console.log instead' appearing in output file

### ISSUE THREAD

**Issue by hunterchristian** [linkedin/dustjs#542]
When running the dustc compiler with node version 0.12, the statement 'util.print: use console.log instead' is being included in the compiled output. This is fixed by replaced every usage of sys.puts/sys.print with console.log, but I want to confirm that this is an existing issue before I submit a pull request.

Example below:
```sh
util.print: use console.log instead
define(['dustjs-helpers'],function(dust){(function(){dust.register("brackets-footer-partial.js",body_0);function body_0(chk,ctx){return chk.write("<div id=\"container-footer\"><p id=\"fancy-p-container\"></p><div>").reference(ctx.getPath(false,["contestinstance","contestname"]),ctx,"h").write("</div><a href=\"\">Terms of Service</a>| <a href=\"\">Privacy Policy</a>| <a href=\"\">Official Contest Rules</a>| <a href=\"\">Contact Us</a>| <a href=\"\">Sign In</a><br><p></p></div></div></div>");}return body_0;})();})
```

**Comment by sethkinast** [comment]
Sounds good to me; I'm not aware of any reason that we used `util.puts` to begin with.

**Comment by hunterchristian** [comment]
Cool, pull request submitted.

**Comment by sethkinast** [comment]
Thanks!
