### ISSUE TITLE
Drop 0.8 support

### ISSUE THREAD

**Issue by jimmyhchan** [linkedin/dustjs#548]
With 0.12 support being added (#546) we should consider dropping support for 0.8. This is very low priority given that things still work in Travis.

Putting this out there for discussion and early warning that 0.8 support will be removed (at some point).

**Comment by rragan** [comment]
Our support cost currently is low for 0.8 as there don’t seem to be problems. That said, as new node versions appear it is a good plan to sunset old ones. I’d say put out a end date sort of warning.

Rich

**Comment by sethkinast** [comment]
It's not as much problems as the desire to do things not supported by 0.8.

Sent while mobile

**Comment by sethkinast** [comment]
Let's target 2.7.0.
