### ISSUE TITLE
Numeric zero as false in "?" construction

### ISSUE THREAD

**Issue by yahorosh** [linkedin/dustjs#551]
Hello!

Dust interprets 0 (numeric) zero as false. In my server side template engine (blitz) same zero is false. Can i ataptate behavior of dust in this case, without injection in dust code?

I'm surprised why in all languages 0 is false and "0" is true, but dust using another logical (maybe from another universe).

Thanks.

**Comment by sethkinast** [comment]
The name of the `{?}` tag is the "exists" tag. It returns true as long as the specified reference exists. Therefore, Dust treats only empty values (`null`, `undefined`, empty Arrays) as nonexistent. Everything else renders the block.

If you want to do a Javascript truth test, you can use the `{@eq}` helper from the `dustjs-helpers` core helpers repository like this:

```
{@eq key=myKeyThatCouldBeZero value="false" type="boolean"}The key is falsy, so it's "false", 0, "0", or something else that Javascript parses as false{/eq}
```

**Comment by jimmyhchan** [comment]
you can also use the section block `{#foo}{/foo}`.  Please check out the wiki https://github.com/linkedin/dustjs/wiki/Dust-Tutorial as well.

Feel free to jump on StackOverflow if this doesn't address your issue. 

Thanks!
