### ISSUE TITLE
Allow contexts to contain Thenables

### ISSUE THREAD

**Issue by sethkinast** [linkedin/dustjs#568]
In theory that sounds fantastic

**Comment by jimmyhchan** [comment]
Can't you just keep writing into the stream?

**Comment by sethkinast** [comment]
The idea would be that if a context contains a Thenable, dust would automatically map an async chunk for it. Mostly sugar.

```
{
  "remoteAPI": $.get("http://example.com/api.json")
}
```

**Comment by sethkinast** [comment]
But the more important aspect is that it allows you to plug in things that don't know about Dust. So if you have a promise-returning module, you can just incorporate that into your Dust render.

This is mostly spitballing; issues are cheap to create.

**Comment by sethkinast** [comment]
Yep this is awesome. PR otw

**Comment by sethkinast** [comment]
To speak a little to Jimmy's objections to Promises:

Promises are definitely a standard. `q` has over 1000 dependents, `bluebird` has over 1000, `rsvp` has 270 more, and jQuery uses Promises for its AJAX handling. Plus, they're a part of native Javascript in ES6.

Dust contexts are not JSON. Forcing them to be JSON requires the removal of context helpers, and I don't think those are going away (or Dust becomes synchronous and uninteresting). Adding support for Promises in context doesn't preclude us from forcing JSON at a later date (it would be a major version bump either way).

Dust contexts intentionally blur the line between current and eventual values. It's already possible to write a context helper that loads data asynchronously-- you could take the code I used to implement Promise handling, and turn it into a context helper, and use it. It's not the job of the template to know where data comes from; this is what makes Dust great! In a way, putting `{magic}` into a template **is already a promise for the eventual value**.

Allowing Promises into the context enables **direct** integration with thousands of Node modules and JS libraries that return Promises. A less-trivial example would be something like this (yes this is a real library)

    var AnimalNamer = require('animal-namer');
    namer = new AnimalNamer();
    tmpl = dust.compile("Your secret animal name is: {username}", "name");
    dust.loadSource(tmpl);
    dust.render("name", { username: namer.name() }, function(err, out) {
      console.log(out);
    });

Without Dust's Promise support, you have to have intimate knowledge of asynchronisity in Dust.

    var AnimalNamer = require('animal-namer');
    namer = new AnimalNamer();
    tmpl = dust.compile("Your secret animal name is: {username}", "name");
    dust.loadSource(tmpl);
    dust.render("name", { username: function(chunk, context) {
      return chunk.map(function(chunk) {
        chunk.end(namer.name());
      });
    } }, function(err, out) {
      console.log(out);
    });

And it gets even worse if your Promise is a `{#section}` instead of just a reference.

Adding Promise support doesn't preclude the addition of other asynchronous data-ingestion methods such as streaming data to a template. Indeed, I plan on submitting a PR for Dust contexts to allow Generators at some point.

I just don't really see a good reason not to make life easier for some subset of people who use Promises as their asynchronous data transfer mechanism of choice.

**Comment by smfoote** [comment]
I am in favor of this change. I like it.
