### ISSUE TITLE
Add grunt-github-changelog

### ISSUE THREAD

**Issue by sethkinast** [linkedin/dustjs#600]
Making changelog manually is no fun.

However, needs the grunt plugin to be updated first.

**Comment by sethkinast** [comment]
https://github.com/streetlight/grunt-github-changes needs to dep a newer version of `github-changes`. I'll submit a PR over there.

**Comment by sethkinast** [comment]
PR https://github.com/streetlight/grunt-github-changes/pull/7 merged, waiting on a new version.

**Comment by streetlight** [comment]
@sethkinast Merged and good-to-go. Thanks!
