### ISSUE TITLE
Documentation for ~n

### ISSUE THREAD

**Issue by cfjedimaster** [linkedin/dustjs#605]
I'm following the documentation and at the filters section, http://www.dustjs.com/guides/using-filters/, ~n is shown:

{title}{~n}

But it isn't documented anywhere. Or maybe it is later in the documentation but if this is really the first time it is used, it should be documented here. From what I can guess it outputs a <br/>.

**Comment by cfjedimaster** [comment]
Ok, I see it is documented in syntax. Still though I think the earlier docs, at least once, should quickly mention it. Certainly in filters where it seemed to stand out more for me.

**Comment by sethkinast** [comment]
Sounds reasonable to me.

**Comment by smfoote** [comment]
@cfjedimaster I think the most logical place for documentation on the Dust specials is in the [Dust Syntax](http://www.dustjs.com/docs/syntax/) section of the site, which is where it is already documented. The second most logical place is in the [Getting Started guide](http://www.dustjs.com/guides/getting-started/), but there is no usage of specials on that page.

In reality, Dust specials are rarely used in real templates, and usually only show up in examples and tutorials. I'm going to close the issue, as Dust specials are documented appropriately in what I deem to be the most logical place.
