### ISSUE TITLE
Add loadSource example to Getting Started Guide

### ISSUE THREAD

**Issue by smfoote** [linkedin/dustjs#614]
An example of how to get Dust to work (without precompiling templates) in the Getting Started Guide will help new users who want to try out Dust without having to set up a server environment.

We should note that compiling templates on the client is not optimal for production use cases.

**Comment by sethkinast** [comment]
I think it would be reasonable to actually have a whole guide on different strategies for getting templates served.

* Compile on client
* Precompile and include script tag
* Precompile and load as AMD
* Compile and cache on server during build process
* Compile using dust.onLoad on the server / a Dust view engine

Currently this info is scattered throughout.

**Comment by smfoote** [comment]
I agree. I do think that a special call out to compiling on the client is worthwhile in the Getting Started guide, because it is a way to "Get Started". However, I don't like how Handlebars, Ember, and others, show examples of how to do things wrong in the Docs, because the wrong way is easier.

I propose a compromise: a link in the Getting Started guide to the new guide that @sethkinast mentioned.

**Comment by sethkinast** [comment]
I'm actually picking this up as part of documentation for #613

**Comment by sethkinast** [comment]
Closed via #628
