### ISSUE TITLE
Is it possible to render an object stream context variable rather than an array?

### ISSUE THREAD

**Issue by bleupen** [linkedin/dustjs#616]
hello,

I am trying to push a node object stream though a dust template, whose output is also streamed. is this possible?

For example: 

```javascript
var recordStream = mydbconn.query('...').stream();
var ctx = {
   records: recordStream
};
dust.stream('myTemplate', ctx); 
```

Thanks

**Comment by sethkinast** [comment]
We've had discussions about how to allow you to stream into a context instead of just streaming templates.

To clarify, what do you expect as the output? Is `myTemplate` a single row that gets rerendered every time a row is streamed in from your database? Or does `myTemplate` wait for the result set to return and then treats the resolved stream as a normal object? (I assume this is node-pg-query-stream or similar.)

The short answer is that currently this is not possible, but you can easily wrap a Stream into an a async chunk. Going forward, I think we could detect Streams and hook this up for you.

```js
var recordStream = mydbconn.query('...').stream();
var ctx = {
  records: function(chunk, context, bodies, params) {
    return chunk.map(function(chunk) {
      recordStream
      .on('data', function(row) {
        chunk.render(bodies.block, context.push(row));
      })
      .on('end', function() {
        chunk.end();
      })
    });
  }
}
dust.stream('myTemplate', ctx);
```

**Comment by bleupen** [comment]
Hi Seth,

Basically, I would like to render a formatted report with header, footer, and a row chunk that is repeated for each row in the result stream. Ideally, the template stream would emit data events as records are processed rather than one event at the end. 

I have it working with chunk.map() at the moment but the entire document is buffered until the result set stream ends.

**Comment by sethkinast** [comment]
Yes, you can do this too! Danger... this is a little arcane. It looks like it would be a great candidate to sugar away in a future release.

The key is that every time you map a chunk, you reserve a new block in the blockstream that can be marked flushable independently.

I wrote up this example using `highland` so it would run in the browser, but you can just drop in your database code.

```js
function() {
  var recordStream = highland([
    { id: 1, name: 'A' },
    { id: 2, name: 'B' },
    { id: 3, name: 'C' }
  ]).ratelimit(1, 1000);

  return {
    records: function(chunk, context, bodies, params) {
      // Master async chunk. Signal to Dust that this entire block will be streamed in
      return chunk.map(function(chunk) {
        recordStream.on('data', function(row) {
          // Every time we get a new record, fork the blockstream and insert another chunk
          chunk = chunk.map(function(chunk) {
            // .end() at the end to immediately flush the forked chunk to the browser
            chunk.render(bodies.block, context.push(row)).end();
          });
        });
        recordStream.on('end', function() {
          // .end() for the master async chunk
          chunk.end();
        });
      });
    }
  }
}
```

**Comment by sethkinast** [comment]
![](http://g.recordit.co/BsYQ9F01Q4.gif)

**Comment by bleupen** [comment]
Sweet, it works! Thank you!

Granted, I've only been working with dust for less than a day so this is probably naiive, but couldn't dust accept an object stream like an array, and just map over it?

**Comment by sethkinast** [comment]
A Stream is just another object as far as Dust is (currently) concerned-- if you try to output it, you'll get [object Object].

I wrote #617 last night to allow Dust to handle Streams in context.

**Comment by sethkinast** [comment]
In Dust 2.7.0 you can now just pass your Stream directly into the context, just like your original example.
