### ISSUE TITLE
Integer and boolean parameters

### ISSUE THREAD

**Issue by gabrielf** [linkedin/dustjs#634]
I think it would be useful if Dustjs supported boolean literals as parameters like this:

```
{@mySweetHelper funkyMode=true /}
```

Currently this will instead search for the key "true" in the current context (which is expected considering the documentation). Integers however _are_ sent as numbers which is something I cannot find in the documentation.

Is this by design or by accident? Regardless I think it should be documented.

Below is a full example showing that booleans does not work (expected but would be nice) but that integers does work (unexpected but perhaps useful).

DustJS-Template:

```
{#booleanParam bool=true/}
{#integerParam int=123/}
```

Data:

```javascript
{
  "booleanParam": function(chunk, context, bodies, params) {
     return chunk.write("bool param is: " + (params.bool ? "true" : "false") + " type: " + typeof params.bool + "\n");
  },
  "integerParam": function(chunk, context, bodies, params) {
     return chunk.write("int param is: " + params.int + " type: " + typeof params.int);
  }
}
```

Result:

```
bool param is: false type: undefined
int param is: 123 type: number
```

**Comment by sethkinast** [comment]
You can pass a `type` param to cast values.

See the Casting section: http://www.dustjs.com/guides/dust-helpers/

**Comment by sethkinast** [comment]
Oh and yes, you can pass numbers unquoted to get them in their raw form. There's no way to disambiguate between the key `true` and the Boolean, though.
