### ISSUE TITLE
undefined stack in context leads to compile errors in 2.7.0

### ISSUE THREAD

**Issue by matthistuff** [linkedin/dustjs#652]
When calling `dust.makeBase`, a new Context with an undefined stack is created (see `lib/dust.js` lines 283 and 274).

This leads to an error when looping over array elements (see `lib/dust.js` lines 761 and following) because there is a check directly on `context.stack.head`.

**Comment by sethkinast** [comment]
To clarify your use, you're trying to render a template with no context (or
only globals)?

**Comment by matthistuff** [comment]
I am kinda trying to do this:

```js
var dust = require('dustjs-linkedin');

var context = dust.makeBase({
    names: [{value: 'a'}, {value: 'b'}]
});

dust.loadSource(dust.compile('{#names}{value}{/names}', 'test'));
dust.render('test', context, function (err, result) {
    if (err) {
        console.log(err);
    }

    console.log(result);
});
```

**Comment by sethkinast** [comment]
OK, generally you would just pass that object directly into dust render
rather than making those global. We'll still fix this.

**Comment by sethkinast** [comment]
Until a 2.7.1 is cut, here's the simplest way to do what you're doing:

```js
var dust = require('dustjs-linkedin');

var context = {
    names: [{value: 'a'}, {value: 'b'}]
};

dust.renderSource('{#names}{value}{/names}', context, function (err, result) {
    if (err) {
        console.log(err);
    }

    console.log(result);
});
```

**Comment by matthistuff** [comment]
@sethkinast, thank you for the clarification and the quick reply.

**Comment by sethkinast** [comment]
Dust 2.7.1 has been released and fixes this behavior.

However generally you probably don't want to put normal data into the global context, as it will be accessible from any scope in your template.
