### ISSUE TITLE
http://yui.github.io/yuicompressor/   (CQ content managment) can't minify full version

### ISSUE THREAD

**Issue by bludrate** [linkedin/dustjs#659]
1304 line. dust v. 2.7.1
peg$c102 = function(char) {return char},

char - is reserved word

**Comment by smfoote** [comment]
Since the line in question is coming from `parser.js`, which is generated by PEG.js (and therefore out of our control), and a minified version of Dust full is already available, I'm going to close this issue.

**Comment by sethkinast** [comment]
We can open an issue upstream instead of just closing his issue

**Comment by sethkinast** [comment]
But in this case it's not even coming from upstream; it's coming from our compiled grammar.

**Comment by sethkinast** [comment]
@bludrate if you need to work around this issue before we release a new version, it will work fine to just rename the `char` variable-- it's not used anywhere else.
