### ISSUE TITLE
Using single quote for partial name

### ISSUE THREAD

**Issue by steverandy** [linkedin/dustjs#665]
Is there a specific reason why only double quotes is allowed for partial name and attributes string value?
For example `{>'includes/test'/}` is invalid.
Is there any plan to support single quote?

**Comment by sethkinast** [comment]
The dust grammar is intentionally strict for speed/ease of parsing.

If you have two quote modes you have to bifurcate the grammar depending on which mode you are in. This drastically increases complexity.

Is there a specific use case for needing single quotes that you have?

**Comment by steverandy** [comment]
Thanks for the explanation. No specific use case, just personal preference to use single quotes.

**Comment by sethkinast** [comment]
If you want to switch the quoting style everywhere, you can edit `src/dust.pegjs` and change the definitions of inline and esc. Then run `grunt build ` to build a new copy of dust.

But then you couldn't use double quotes.
