### ISSUE TITLE
Nested comments don't work as expected

### ISSUE THREAD

**Issue by jv-PintoBobcat** [linkedin/dustjs#666]
If you have nested comments, the very first comment close tag ends the comment.

`{! test {! me !} please !}`
renders
`please !}`

I'm seeing this against version 2.7.1.  I haven't checked earlier versions.

Is this part of the spec of dust or is this a bug?

**Comment by sethkinast** [comment]
This is the same way that comments in HTML work :)

**Comment by sethkinast** [comment]
So in HTML and Dust, comments basically turn off the parser. The tokenizer stops looking for all tokens EXCEPT the "end comment" token.

    {! comment {ref} {%pragma} {! whatever

Everything after an opening comment is ignored until you get to `!}` which means that there is no such thing as a "nested" comment-- it's simply a string of characters between `{!` and `!}`

HTML is the same:

     yay the end of a comment with an arrow after it -->

Javascript is the same:

    /* some stuff including a slash-star /* */ alert(1); */      // Syntax error

So nested comments work exactly as expected.
