### ISSUE TITLE
Default is depreciated

### ISSUE THREAD

**Issue by DavidMoritz** [linkedin/dustjs#670]
Please remove it from your wiki.
https://github.com/linkedin/dustjs/wiki/Dust-Tutorial#select-keyxxx--eq-ne-lt-lte-gt-gte-default-available-in-dust-10

**Comment by sethkinast** [comment]
The wiki is deprecated in favor of http://dustjs.com

**Comment by DavidMoritz** [comment]
Fair enough. That's a pretty cool page. Thanks for the link!

**Comment by sethkinast** [comment]
Added a deprecation notice to the wiki pages.
