### ISSUE TITLE
Support for compound filters?

### ISSUE THREAD

**Issue by tkambler** [linkedin/dustjs#677]
Has anyone considered adding support for compound filters? For example, let's say that I've created two custom filters - `humanize()` and `capitalize()`. I would be able to apply them both, as shown below.

#### Context
```
{
    "education": "high_school"
}
```

#### Template
```
Joe has a {education|humanize|capitalize} education.
```

#### Template (Alternative Syntax)
```
Joe has a {education|humanize,capitalize} education.
```

#### Result
```
Joe has a High School education.
```

**Comment by sethkinast** [comment]
This should work exactly as you expect. Each filter will receive the output
of the previous step, left to right.

**Comment by tkambler** [comment]
Hmm... I had expected that it would, too, but it doesn't appear to be. Let me investigate, will report back.

**Comment by tkambler** [comment]
Problem was on my end. This works as expected.

**Comment by jimmyhchan** [comment]
I believe that's already supported. 

Custom filters just requires that you add to the dust.filters global.
