### ISSUE TITLE
$idx is undocumented

### ISSUE THREAD

**Issue by Tvrqvoise** [linkedin/dustjs#679]
The only reference I can find to ```$idx``` on the new Dust website is in the helpers section, wherein it's mentioned during an example of the math helper:
http://www.dustjs.com/guides/dust-helpers/#math-helper

It would be helpful if $idx was explained as a part of the looping syntax.

**Comment by Tvrqvoise** [comment]
The same thing is true of $len

**Comment by sethkinast** [comment]
Thanks!
