### ISSUE TITLE
Cannot iterate context array with table tr

### ISSUE THREAD

**Issue by nikolaygit** [linkedin/dustjs#682]
If I have a context
``` javascript
{
  rows: [ {id: 1}, {id: 2} ]
}
```
and try to render it within a HTML table
``` html
<table>
{#rows}
<tr>
  <td>{id}</td>
  <td>not visible wrapped tr. Two rows expected.</td>
</tr>
{/rows}
<table>
```
I get as a result:
``` html
not visible wrapped tr. Two rows expected.
```
instead of two table rows with the ids.

I reproduced the issue on:

* Codepen: http://codepen.io/nikolayhg/pen/OVjPeN?editors=101
* JsFiddle: http://jsfiddle.net/ww38ffd7/
* Plnkr: http://plnkr.co/edit/vX8TXoiXf4XUAmh5o2WW?p=preview
* or a file: http://www.unupload.com/download/d4yky4ja98k24zoeh0an41p7er4cccsy6ox3u7v6

Surprisingly on the dustjs test page it worked as expected! https://linkedin.github.io/dustjs/test/test.html

Any thoughts what may be the problem?

**Comment by sethkinast** [comment]
It's because you're getting the innerHTML of a `div`, and text content outside of a `<tr>` isn't supported by HTML. So when the browser calculates innerHTML, it strips the invalid pieces (in this case the section iterator `{#rows}`.

You should use `script` tags to store your templates, like this:

http://jsfiddle.net/ww38ffd7/2/

```
<script type='text/dust' id="template">Hello {dust}!</script>
<div id="container"><!-- render here --></div>
```

**Comment by sethkinast** [comment]
This is covered in our [basic browser](http://www.dustjs.com/guides/rendering/#browser-basic) example in the docs.

Of course once you start using Dust for real you should precompile your templates instead of including them as inline script tags.

**Comment by nikolaygit** [comment]
Thank you @sethkinast for the good explanation!
