### ISSUE TITLE
Using a partial inside a helper context prevent the dust.render callback to be called

### ISSUE THREAD

**Issue by shaoner** [linkedin/dustjs#686]
Hi,

It seems that when having a partial in a helper context, the render function does not call the given callback when templates are retrieved with dust.onLoad.
Here is a simple example to reproduce the issue:

```js
var dust = require('dustjs-linkedin');

var templates = {
    hello: 'Hello World',
    test1: 'Test: {@foo}{>"hello"/}{/foo}!',
    test2: 'Test: {@foo}Hello World{/foo}!',
    test3: 'Test: {>"hello"/}!'
};

dust.helpers.foo = function (chunk, ctx, bodies, params) {
    chunk.write('[');
    chunk.render(bodies.block, ctx);
    chunk.write(']');
    return chunk;
};

dust.onLoad = function (templateName, callback) {
    if (templateName in templates) {
        return callback(null, templates[templateName]);
    }
    callback(new Error('unknown template ' + templateName));
};

dust.render('test1', { }, function (err, res) {
    debugger; // This is never called
    console.log(err, res);
});

dust.render('test2', { }, function (err, res) {
    console.log(err, res); // null 'Test: [Hello World]!'
});

dust.render('test3', { }, function (err, res) {
    console.log(err, res); // null 'Test: Hello World!'
});
```

Somehow, the last chunk is not valid, so it just returns here https://github.com/linkedin/dustjs/blob/master/lib/dust.js#L564 without sending back the result.

This only happens when the template is not originally in the dust cache.
For example, this works as expected:

```js
var dust = require('dustjs-linkedin');

var templates = {
    hello: 'Hello World',
    test1: 'Test: {@foo}{>"hello"/}{/foo}!',
    test2: 'Test: {@foo}Hello World{/foo}!',
    test3: 'Test: {>"hello"/}!'
};

dust.helpers.foo = function (chunk, ctx, bodies, params) {
    chunk.write('[');
    chunk.render(bodies.block, ctx);
    chunk.write(']');
    return chunk;
};

// dust.onLoad = function (templateName, callback) {
//     if (templateName in templates) {
//         return callback(null, templates[templateName]);
//     }
//     callback(new Error('unknown template ' + templateName));
// };

for (templateName in templates) {
    dust.loadSource(dust.compile(templates[templateName], templateName));
}

dust.render('test1', { }, function (err, res) {
    debugger;
    console.log(err, res); // null 'Test: [Hello World]!'
});

dust.render('test2', { }, function (err, res) {
    console.log(err, res); // null 'Test: [Hello World]!'
});

dust.render('test3', { }, function (err, res) {
    console.log(err, res); // null 'Test: Hello World!'
});
```

**Comment by sethkinast** [comment]
Thanks for the great report. I will take a look this weekend.

**Comment by sethkinast** [comment]
Oh, without actually running your code yet (so this is just perfunctory) but I think you have an error in your code.

When you call `chunk.write` or `chunk.render`, the return value is a Chunk.

In the case of `chunk.write`, the return value is the same Chunk as the Chunk that you invoked `write` on, so you don't need to worry about capturing the return chunk.

In the case of `chunk.render`, the Chunk invokes the template you'd like to render. **If this template is asynchronous** (for example it uses `chunk.map` somewhere), then a new Chunk will be forked out of the chain to handle this asynchronous template. That means that the return value of `chunk.render` is not always the same chunk that you called `render` on.

So in a helper, when calling `render`, you need to capture the chunk that is passed back, like this:

```
dust.helpers.foo = function (chunk, ctx, bodies, params) {
    chunk.write('[');
    chunk = chunk.render(bodies.block, ctx);
    chunk.write(']');
    return chunk;
};
```

Or like this:

```
dust.helpers.foo = function (chunk, ctx, bodies, params) {
    return chunk.write('[').render(bodies.block, ctx).write(']');
};
```

Otherwise, the async chunk will never be flushed.

**Comment by sethkinast** [comment]
Behold my bad ASCII art.

When you render the template and have it include a partial, it creates a second chunk. While the second chunk is rendering, the parent is marked unflushable (or else there would just be a blank space where the second chunk should go).

If you lose track of the new chunk (by not capturing the result of `chunk.render`), the parent chunk is never marked flushable, so you hang forever.

```
+-Flushable------+                            
|                |                            
| data: []       |                            
| head: func()   |                            
| tail: null     |                            
|                |                            
+----------------+                            
                                              
+-Flushable------+                            
|                |                            
| data: ["Hello"]|                            
| head: func()   |                            
| tail: null     |                            
|                |                            
+----------------+                            
                                              
+-NOT Flushable--+          +----------------+
|                |Create and|                |
| data: ["Hello"]|disable   | data: []       |
| head: func()   +----------> head: <Chunk>  |
| tail: <Chunk>  |flushable | tail: null     |
|                |          |                |
+----------------+          +----------------+
                                              
+-Flushable------+Done with +----------------+
|                |render so |                |
| data: ["Hello"]|set parent| data: ["World"]|
| head: func()   <----------+ head: <Chunk>  |
| tail: <Chunk>  |flushable | tail: null     |
|                |          |                |
+----------------+          +----------------+
```

**Comment by shaoner** [comment]
Oh, yes, totally forgot about `chunk.map` creating new chunks before dust.onLoad to be called!
I was too focus on the different behavior with / without dust.onLoad.

Actually even some popular external helpers like `@provide` and examples at http://www.dustjs.com/docs/helper-api/ don't re-set the chunk after rendering, and most of the time this is fine enough.

Thanks for the great explanation! (and the ascii-art is not so bad)

**Comment by sethkinast** [comment]
Thanks for noting that the documentation is not correct, we'll get that fixed.
