### ISSUE TITLE
Dust loading twice with r.js optimizer

### ISSUE THREAD

**Issue by jasonmerino** [linkedin/dustjs#687]
I'm having an issue with using the new AMD enabled version of dust in the browser with the r.js optimizer. The dust libraries get packaged up nicely into the main script that I load on the page, but when I load up the page in the devtools network pane I see the entire main script request and then separate requests for dust-core and dust-helpers.

I've worked up a demo repo with the issues I'm running into. It's basically the AMD example project in this repo with the addition of the r.js optimizer.

https://github.com/jasonmerino/dustjs-amd-optimizer

It's entirely possible that I'm configuring something incorrectly, but I've been messing with it for a couple days now and I'm going bonkers!

**Comment by sethkinast** [comment]
You're not setting `define.amd.dust = true` high enough.

That config needs to be set before the Dust files execute, or they won't be registered as AMD-aware, so require will go try to find them on the network.

**Comment by jasonmerino** [comment]
Ahhhhh. I see. That fixed it.

Thanks!
