### ISSUE TITLE
document allowable formats for templateName 

### ISSUE THREAD

**Issue by wirehead** [linkedin/dustjs#688]
in http://www.dustjs.com/docs/api/ the parameter templateName isn't documented.

Specifically, only certain characters are allowed.  alphanumeric characters are OK, but a number of special characters (e.g. '/' and ' ') are forbidden.

**Comment by sethkinast** [comment]
All names should be OK-- Dust escapes the name before using it as a cache key.

What names are you having trouble using?

```
$ bin/dustc --name="Hello /World"
(function(dust){dust.register("Hello \/World",body_0); ...
```

**Comment by sethkinast** [comment]
Please let us know if there are characters you find yourself unable to use in a template name.

**Comment by wirehead** [comment]
I was able to undo my confusion:

You can use Dust partial names without quoting.  e.g. `{>template-name/}`.  In that case, spaces or slashes are bad.

In http://www.dustjs.com/docs/syntax/ , quoting is not mentioned and the examples are unqouted.  In http://www.dustjs.com/docs/api/ , quoting is also not mentioned and the examples are quoted.  I suspect in the syntax reference section, you want to explain that quoting is optional, but you probably want to quote template names as then you don't wonder why slashes and other characters don't work the way you think they do.

**Comment by sethkinast** [comment]
Got it. We can elaborate there, thanks!

**Comment by sethkinast** [comment]
I updated the docs a bit. Thanks for the feedback!

**Comment by wirehead** [comment]
Thanks!  Sorry I didn't have the right doc suggestion right off.
