### ISSUE TITLE
[Question]: Render partial via a Helper

### ISSUE THREAD

**Issue by peduarte** [linkedin/dustjs#694]
I'm trying to abstract some code and would like to take advantage of dust.helpers to render a parial.

My current setup:

    {> "includes/components/link" /}

My **ideal** setup:

    {@uiComponent name="link" /}

**My helper:**

    dust.helpers.uiComponent = function (chunk, context, bodies, params) {
        return dust.render('includes/components/' + name, context, function (err, out) {
            chunk.end(out);
        });
    };

I have also tried a number of other things and nothing works.

And yes, I tried looking at the documentation. :(

Any advice would be much appreciated!

**Comment by sethkinast** [comment]
You just asked this on StackOverflow and I started responding there-- that's a venue more suited to questions about using Dust :)

**Comment by peduarte** [comment]
Yeah! haha thanks so much! :smiley:

**Comment by peduarte** [comment]
Hey, just wanted to say thanks once again, that solved my problem.
