### ISSUE TITLE
Broken link in http://www.dustjs.com/guides/dust-helpers/

### ISSUE THREAD

**Issue by brynnbp** [linkedin/dustjs#697]
There is a link to here:
http://www.dustjs.com/docs/helpers-api/

which doesn't exist. The correct URL is "helper" (singular):
http://www.dustjs.com/docs/helper-api/

on this page:
http://www.dustjs.com/guides/dust-helpers/

Not sure if this repo is the right place to point this out but I see no other options.

**Comment by brynnbp** [comment]
Also worth noting the guide has this sentence:

"A full list of values that the method attribute can take is found in the Helpers API documentation."

but when you got to the doc page for helpers, there are no references to acceptable @math methods.

**Comment by sethkinast** [comment]
Thanks! Will update.
