### ISSUE TITLE
Check if template exists

### ISSUE THREAD

**Issue by peduarte** [linkedin/dustjs#698]
Hey guys

I am trying to create a Dust Helper to render a collection of templates.
However, I need to check whether they exist before rendering.

This is what I currently have:
```js
   dust.helpers.renderIfExists = function (chunk, context, bodies, params) {
        var template = context.resolve(params.template);
        return chunk.partial(template, context, params);
    };
```

This successfully render templates that do exist, however, if one doesn't it throws an error:
```
error: E500-1441359713287 Error: ENOENT, open ...path...
```

Can anyone here help me please?

Thanks

**Comment by peduarte** [comment]
:(

**Comment by rragan** [comment]
Some time back I threw together a helper to use if you needed to determine if a partial existed before calling it. Not sure if it works with the large number of changes made to dust since I wrote it but it could be a starting point.

Usage:
{@ifPartial name="dropdown"}
   randomeJunk found
{:else}
 random not foundxxxxxxxxxxxxxxxxxxxxx
{/ifPartial}

dust.helpers.ifPartial = function provide(chunk, ctx, bodies, params) {
'use strict';
	var name = dust.helpers.tap(params.name, chunk, ctx),
		skip = bodies['else'];

	if (dust.cache[name]) {
	   return chunk.render(bodies.block, ctx);
	}
	if (skip) {
		return chunk.render(skip, ctx);
	}
	return chunk;
}

**Comment by sethkinast** [comment]
The default behavior of `dust.onLoad` is to throw an error. If you want to fail silently, just provide your own implementation of `dust.onLoad`.

See http://www.dustjs.com/guides/onload/

(Also, your first message was at 2:30 am for everyone that works on Dust, so adding extra messages with sad faces after 6 hours is not constructive. Thanks!)

**Comment by peduarte** [comment]
Thanks for the replies.

@sethkinast I'm sorry if the sad face offended you. I assumed dustjs had collaborators around the world, like most libraries by big corporations (Google, Facebook,...) I wasn't aware that there was a specific team working on it.
With all due respect, I would prefer to find these answer while reading the documentation – but I was unable to 😉

Also, I am surprised there is no native way to check whether a template exists or not, it's a pretty common feature, not an edge case.

Anyway, again, thanks for the replies, I'll implement something myself based on the answers.
