### ISSUE TITLE
dust.indexInArray() removed?

### ISSUE THREAD

**Issue by kodeninja** [linkedin/dustjs#702]
We reference `"dustjs-linkedin": "^2.4.0"` in our package.json. Recently, `npm install` pulled in `dustjs-linkedin@2.7.2` and it seems that the `dust.indexInArray` api has been removed. We reference this method to setup log levels on the `dust` object. Obviously, this no longer works.

So, why was this method removed? The changelog doesn't talk about this either, so, were we relying on an internal API?

**Comment by sethkinast** [comment]
Yeah, that was just an internal function for IE8 compat (used for logging levels internally too!) It was not documented for external use, sorry :(

The most recent version with the function available was 2.6.1, if you want to pin against that.

Relevant commit: https://github.com/linkedin/dustjs/commit/c9c8df67b8470c3152efd31e902eac680dab5b02

**Comment by kodeninja** [comment]
Thanks for confirming that, @sethkinast! We'll modify the code to not rely on this API. It was available directly off the `dust` object and issued no warnings when used, so we thought it was safe to use.

**Comment by sethkinast** [comment]
Yeah, historically private apis do not have a good track record of being
actually private. We'll be better about this going forward. Sorry for the
trouble.
