### ISSUE TITLE
how to modify dust file without restarting the project

### ISSUE THREAD

**Issue by simonchan2013** [linkedin/dustjs#704]
hello, if I modify the dust file, is there any method to make the change work without restarting the project?
wish your response, thanks

**Comment by sethkinast** [comment]
It depends on how you're using Dust. If you are using it with a simple Express server or something, just clear `dust.cache` when you detect a change.

If your templates are delivered client-side, you can just recompile the changed file.

**Comment by simonchan2013** [comment]
thanks, I think I should clear `dust.cache`
