### ISSUE TITLE
Provide partial template location as variable.

### ISSUE THREAD

**Issue by killfish** [linkedin/dustjs#709]
Is something like this possible?

Data sample:
`var data = {
   template : 'some/location/test
}`

Template sample:
`<p>render partial based off of data.template value</p>
{> data.template /}`

That does not work but I was wondering if there is another way to accomplish this.

**Comment by sethkinast** [comment]
Try {> "{data.template}" /}

**Comment by smfoote** [comment]
This question is probably best addressed on StackOverflow. Also, you probably want `{>"{template}"/}`, and not `{>"{data.template}"/}`.

**Comment by killfish** [comment]
That works! Many thanks.
