### ISSUE TITLE
Your current documentation does not actually have the truthiness section.

### ISSUE THREAD

**Issue by ftrotter** [linkedin/dustjs#711]
So you should add it back.

**Comment by aarongodin** [comment]
By truthiness, you mean that `{?exists}` is actually `{?truthy}`? And correspondingly `{^not-exists}` would be `{^falsy}`?

Just clarifying as this is the issue I came to report as well. Definitely tripped me up.

**Comment by ftrotter** [comment]
Yes. In parts of the documentation it actually says "look over here for more information about truthiness" and then when you do it is not covered. 

This is one of many issues that was better covered in the old github wiki.

-FT
