### ISSUE TITLE
You obviously need some basic string functions

### ISSUE THREAD

**Issue by ftrotter** [linkedin/dustjs#712]
You defined it in your example which was ironically meeting demand. 

Then there is this:
https://www.npmjs.com/package/dustmotes-substr
and this:
https://github.com/linkedin/dustjs/issues/206
and this:
http://codyburleson.com/2014/10/24/string-replace-helper-for-dust-js/
and this:
http://stackoverflow.com/questions/18403990/truncating-returned-data-in-dust-js-template

is that you are forcing other developers to go to third party solutions for functionality that should obviously included in your core or your helpers. 

I have no intention of coding my own helper. Like most application developers I am looking for a library that just solves the problem, rather than asking me to code around it to satisfy the "packaging ideology" of the original developers.

Regards,
-FT

**Comment by jimmyhchan** [comment]
Thanks for the feedback.

While we can definitely debate the intentions of the original developers and the ideology that led to the decision to keep the core small and focused, but the truth is unless there's an overwhelming push to get this modified from core contributors and the community including string helpers into core (IMO) will not happen. (disclaimer: I for one would prefer string functions to not be in this repo.)

For more reading check out #181
