### ISSUE TITLE
Can't conditionally set inline partial contents

### ISSUE THREAD

**Issue by jv-PintoBobcat** [linkedin/dustjs#718]
```dust
{+partial/}

{@eq key=0 value=1}
  {<partial}This shouldn't appear.{/partial}
  Neither should this.
{/eq}
```

Given the above template, it renders "This shouldn't appear."  I wouldn't have expected that.  Is this behavior intentional?

**Comment by smfoote** [comment]
Inline partial definition does not respect conditionals of any kind. This is known behavior, and has been the same since Dust was first created. In that sense it is expected, but I can't say that this is intentional behavior.

**Comment by jv-PintoBobcat** [comment]
I was attempting to use conditional inline partials as a last ditch effort for dealing with a particularly troublesome bit of logic.  Maybe you can recommend a better way.

Here's the logic.
```
If (foo.foo exists && foo.bar == 2) or
   (foo.foo exists && foo.bar == 1) or
   (bar exists) or
   (baz.foo == 1 && baz.bar > 0) or
   (baz.foo == 1 && baz.baz > 0)
      Render some text
Else
      Render nothing
```

**Comment by sethkinast** [comment]
This is totally logic that should go in a helper, not in your template. Dust intentionally tries to help you keep complicated domain logic out of templates.

```
{#testThing}Render some text{/testThing}

{
  testThing: function(chunk, context) {
    var foofoo = context.get('foo.foo'),
        foobar = context.get('foo.bar');
    return (foofoo && (foobar === 1 || foobar === 2)) || // etc...
  }
}
```

**Comment by sethkinast** [comment]
The static registration of inline partials is a Dust behavior that's not likely to change. Closing this for now, but let me know if the helper doesn't work for you.
