### ISSUE TITLE
The @first and @last

### ISSUE THREAD

**Issue by yahorosh** [linkedin/dustjs#720]
Why

```
{@first}
A
{:else}
B
{/first}
``` 

is don't work? How to decorate first or last iteration?

**Comment by sethkinast** [comment]
`first` and `last` are part of dustjs-helpers, so make sure you're pulling the helpers in.

Then, you need to iterate over an array in your context to make first and last work, since they kick in during the first and last items in the array.

```
{#guests}
  {@first}Hello {/first}
  {@last}and {/last}
  {.}{@sep}, {/sep}
  {@last}!{/last}
{/guests}
```

**Comment by sethkinast** [comment]
`{:else}` in first and last is not a thing currently, but that seems reasonable to add.

**Comment by yahorosh** [comment]
Ok. Thanks

So, i just rewrite helper "first" 

```javascript
dust.helpers.first = function(chunk, context, bodies) {
                if (context.stack.index === 0) {
                  return bodies.block(chunk, context);
                } else {
                  return bodies.else(chunk, context);  
                }
          return chunk;
};
```
