### ISSUE TITLE
Would it be possible to include a block as string?

### ISSUE THREAD

**Issue by yPangXie** [linkedin/dustjs#724]
I want to use the dustjs template engine to render a template from the client browser. The template is rendered by the server function. My solution is: Store them in a hidden textarea. Would it be possible to include a block as string??

Demo below.

**home.dust**

```html
<h1>It's my blog</h1>
<textarea style="display: none;" id="demo">
{> "snippet/product_list_template" /}
</textarea>
```

**snippet/product_list_template**
```html
<ul>
{#list}
    <li>{product_name}:{product_price}</li>
{/list}
</ul>
```

I hope the output html would be:
```
<h1>It's my blog</h1>
<textarea style="display: none;" id="demo">
<ul>
{#list}
    <li>{product_name}:{product_price}</li>
{/list}
</ul>
</textarea>
```

**Comment by sethkinast** [comment]
If you don't want to evaluate the Dust inside a template, use the backtick "escape" pragma:

```
{`
<ul>
{#list}
    <li>{product_name}:{product_price}</li>
{/list}
</ul>
`}
```

**Comment by yPangXie** [comment]
It's awesome!! Thanks @sethkinast !!
