### ISSUE TITLE
Helper API with Bootstrap 3 Inconsistent Behaviour

### ISSUE THREAD

**Issue by hasancansaral** [linkedin/dustjs#728]
I have a helper where I apply some acl logic as follows:

```
'use strict';

import dust from 'dustjs-linkedin';
import acl from '../config/acl';

dust.helpers.accessControl = function(chunk, context, bodies, params) {
    let userId = params.userId;
    let resource = params.resource;
    let permission = params.permission;

    acl.acl.isAllowed(userId, resource, permission, function(err, res){

        if(res){
            chunk.render(bodies.block, context);
            return chunk;
        }
        else {
            return chunk;
        }
    });
};
```
and in the template:

```
{@accessControl userId=user._id resource="/admin" permission="get"}
                    <li class="nav-item">
                        <a class="nav-link" ng-class="{'active' : getPath()[0] == 'admin'}" href="/admin">Admin</a>
                    </li>
{/accessControl}
```

The helpers gets called correctly with correct params, and node_acl authorizes the user correctly (`res` in the callback is `true`). At many places within my templates, it displays the intended behaviour, except for the Bootstrap 3 navbar, where it usually renders nothing, and sometimes below the ul in the navbar: [Screenshot](http://i.stack.imgur.com/4jt5N.png) 

In addition, for the list items I use it, the order of them are changing when I am applying the helper to some of the list items. If I apply to all, it's safe and displays the intended behaviour. What is wrong (or what am I doing wrong, most probably)? Thanks!

**Comment by jimmyhchan** [comment]
Please reduce your code example down to something more specific. For example, what value are you expecting from Dust, from what function call? Please step through this some more and hopefully reduce the problem to something without acl, BootStrap and Angular.

It's going to be very difficult to act on this issue with so many other unrelated variables.

**Comment by sethkinast** [comment]
Is your acl function asynchronous?

**Comment by hasancansaral** [comment]
@sethkinast It is sync according to the documentation, but I will treat it as async and promisify to see what's going on. @jimmyhchan Angular is out of the way already.

**Comment by sethkinast** [comment]
OK, if it were asynchronous (based on having a callback), that would be a
pretty good explanation for out-of-order chunks. You want to use Chunk.map
or return Promises out of your helper if there's any asynchronisity.

**Comment by sethkinast** [comment]
Is this the node one? It doesn't look sync :
https://github.com/OptimalBits/node_acl/blob/master/lib/acl.js#L524

**Comment by hasancansaral** [comment]
It turned out to be a wrongly documented fork of it.

```
return chunk.map(function(chunk) {
        acl.acl.isAllowed(userId, _reverse(resource), permission, function(err, res){
            if(res && bodies['block']) {
                return chunk.render(bodies['block'], context).end();
            }
            else {
                return chunk;
            }
        });
    });
```

immediately resolved the out-of-order chunks issue. Sorry for this.

**Comment by sethkinast** [comment]
If the fork has promise generation capability you can simplify the helper
to just return a promise for true or false, and that will signal the body
to render as appropriate.

**Comment by hasancansaral** [comment]
@sethkinast Thanks, but this did not seem to work for me:

```
dust.helpers.accessControl = function(chunk, context, bodies, params) {
    let userId = params.userId;
    let resource = params.resource;
    let permission = params.permission;

    acl.acl.isAllowed(userId, _reverse(resource), permission).then(function (result){
        return new Promise(function(resolve, reject){
            resolve(result);
        })
    });
};
```

**Comment by sethkinast** [comment]
You're not returning the promise from the helper.

**Comment by sethkinast** [comment]
That's a promise antipattern even. Just return the promise returned by the
acl function, don't do all that promise re-creation stuff.
