### ISSUE TITLE
{?exists/} and {^not-exists/} don't resolve promises

### ISSUE THREAD

**Issue by kahlin** [linkedin/dustjs#732]
`{?exists}`  and `{^not-exists}` don't resolve promises, but rather they just check if the value is falsey or not. If they are given a promise they will treat it as true since it's not null or false.

It surprised me that it works this way. It is the intended behavior or is it a bug? If it is the intended behavior, I'd be happy to create a PR with updated docs to make it more obvious. =)

**Comment by sethkinast** [comment]
So this is the intention, just to stick more closely to how Dust treats other values. For example, if you feed `{?exists}` a context helper, it doesn't evaluate the helper; it just checks to see if something is there or not.

You have a couple options, though. If you're trying to use exists, a section tag has the same semantics:

```
{#promiseThing}
truthy!
{:else}
falsy.
{/promiseThing}
```

Or if you're trying to check something inside the promise, you can unpack it first:

```
{#promiseThing}
{?thingInsidePromise}truthy{:else}falsy{/thingInsidePromise}
{/promiseThing}
```

**Comment by kahlin** [comment]
That makes the behavior of `{?exists}` consistent, it just wasn't the behavior I assumed. I ended up using something similar to what you're suggesting. Thanks for the explanation!

**Comment by sethkinast** [comment]
If you'd like to add anything to the docs, we'd gladly take it! Could probably roll into https://github.com/linkedin/dustjs/issues/711 at the same time :+1:
