### ISSUE TITLE
Fix npm warning for deprecated minimatch@0.3.0

### ISSUE THREAD

**Issue by remarkablemark** [linkedin/dustjs#738]
When installing the package, I receive the following error:
```sh
$ npm install dustjs-linkedin
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

It seems like the issue has already been resolved in f7906e4 when the `cli` dependency was bumped.

So would it be possible to do a **release** to fix the warning? Much appreciated for all your work!

**Comment by sethkinast** [comment]
There are some changes that make a patch release non ideal, I'll see about
a minor release next week.

**Comment by grawk** [comment]
Is it planned to port this fix back to `2.6` as well?

**Comment by sethkinast** [comment]
No, we generally only backport security issues. Any particular reason you're still on 2.6?

**Comment by grawk** [comment]
From http://krakenjs.com/2015/07/06/new-i18n-for-dust.html:

```
Dust 2.7 came out and broke one key interface that Kraken’s adaro had relied on. dust.load was moved internal, where before it was just undocumented private method exposed to the world. Because of this, adaro’s hacks to override the loader no longer work...
```

Because we adopted dust via our adaro module several years ago, many of our applications are currently bound to dust <=2.6. We have a new system that uses >=2.7 but it requires a lot of refactoring. Our timeline for being completely off of <=2.6 is the end of this year.

Meanwhile, the known minimatch vulnerability is causing build warnings. We want to eliminate all usage of the affected versions of minimatch ASAP. But, again, our timeline for upgrading to dust 2.7 and above cannot be moved up.

This seems like a "security" issue. If there are no breaking changes between cli 0.6 and cli 0.11, it would be very helpful if we could get a patch for this in the meantime.

**Comment by sethkinast** [comment]
Thanks for the extra info. It seems reasonable to backport only the affected dep bump (rather than the entire commit)

**Comment by sethkinast** [comment]
```$ npm ls minimatch
dustjs-linkedin@2.6.2
├─┬ cli@0.6.6
│ └─┬ glob@3.2.11
│   └── minimatch@0.3.0
├─┬ grunt@0.4.5
│ └── minimatch@0.2.14
├─┬ grunt-contrib-jshint@0.11.3
│ └─┬ jshint@2.8.0
│   └── minimatch@2.0.10
└─┬ grunt-template-jasmine-istanbul@0.3.4
  └─┬ istanbul@0.3.22
    └─┬ fileset@0.2.1
      └── minimatch@2.0.10```

**Comment by sethkinast** [comment]
There are a pretty good chunk of deprecations even in 2.7.2, any reason you are singling the minimatch one out in particular?

```
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@2.0.1: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.5.1: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
```

**Comment by sethkinast** [comment]
Oh you're probably doing a production install (which is good). OK, this sounds reasonable.

**Comment by grawk** [comment]
Right. We run a security check over our shrink-wrapped builds, and minimatch is the only one which causes any warnings.

**Comment by rmg** [comment]
@sethkinast is there anything anyone can do to help get a release out with the dependency updates?

I've got a small app running in production that is pulling dustjs directly from this repo and it hasn't had any problems yet, if anecdata helps :-P

**Comment by sethkinast** [comment]
Sorry for delay, I'll get to it this weekend and just do patch releases
with the CLI bump instead of trying to backport

**Comment by sethkinast** [comment]
OK, 2.6.3 and 2.7.3 should make it through our release process today and onto CDNs by tomorrow.

**Comment by sethkinast** [comment]
2.6.3 and 2.7.3 are available on NPM. Should hit CDNJS tonight.

**Comment by remarkablemark** [comment]
Thanks @sethkinast for the release!

**Comment by grawk** [comment]
Yes, thanks a lot!

**Comment by rmg** [comment]
Doh! And now `nsp` is complaining about `cli` and `snyk` is complaining about the version of the [very deeply] nested `tough-cookie`.

But now that I'm looking at it.. `cli` and `chokidar` are the only dependencies `dustjs-linkedin` has, and they are only used for the `dustc` command. It's kind of unfortunate that those are being pulled in and tripping alarms when I don't even use/want the CLI. That would be a pretty annoying refactoring, though, given all the things it would affect :-/
