### ISSUE TITLE
Update dependencies to avoid security alert

### ISSUE THREAD

**Issue by MattLds** [linkedin/dustjs#748]
Hi,

Here is a check of your dependencies : 

Vulnerability test : https://snyk.io/test/npm/dustjs-linkedin
Same result with nodesecurity.io

Could you update the version of `cli` to 1.x.x or switch it to dev dependencies if possible.

Thanks,

**Comment by danactive** [comment]
Fixed, let's get my PR merged!

**Comment by jimmyhchan** [comment]
Patch is in 2.7.5  which should show up shortly. Thank you @danactive!
