### ISSUE TITLE
CHANGELOG.md is outdated

### ISSUE THREAD

**Issue by jpw** [linkedin/dustjs#749]
eom

**Comment by sethkinast** [comment]
The latest version of Dust is 2.7.4. The changelog contains changes up until 2.7.4.

https://github.com/linkedin/dustjs/blob/2.7/CHANGELOG.md

eom

**Comment by jpw** [comment]
Ah, I was looking in master not the 2.7 branch. I assumed that releases would be merged into master.
https://github.com/linkedin/dustjs/blob/master/CHANGELOG.md
