### ISSUE TITLE
Use filters in exists section

### ISSUE THREAD

**Issue by gilly3** [linkedin/dustjs#750]
I have a filter that returns a value or null:

```javascript
dust.filters.zip = function(s) {
    return /^\d{5}/.test(s) ? s : null;
};
```

It would be nice to be able to evaluate that filter in an exists (or not-exists) section:

```
{?data|zip}
    <!--has zip-->
{:else}
    <!--no zip-->
{/data|zip}
```

This doesn't work currently.  As a work around, I'm using `{@eq}`:

```
{@eq value="" key="{data|zip}"}
    <!--no zip-->
{:else}
    <!--has zip-->
{/eq}
```

The exists section syntax would be a nice feature.

**Comment by jimmyhchan** [comment]
Have you tried writing a helper?

**Comment by gilly3** [comment]
A helper isn't much better than `{@eq}`.  This is a pattern that I foresee potentially wanting to use frequently.  It would be nice to use the same, familiar syntax.

**Comment by sethkinast** [comment]
I'm mostly worried about overloading the filters syntax; filters are supposed to be transformers, not validators. The only case in which it makes sense to be able to use a filter in an ?exists is if the filter conditionally returns something falsy, which I'm not sure about.

It also starts introducing cognitive overhead of "where can I use filters"-- can I use them in sections now? Or helpers?

**Comment by sethkinast** [comment]
I think the `{@eq}` helper is a nicer solution, really. The nicest solution is definitely just turning your filter into a helper. If you want to use it frequently with different sorts of patterns, maybe a cool `@validate` helper that takes a `pattern` as a param. Helpers can render more blocks than just `:else` as well.

**Comment by gilly3** [comment]
Fair enough.  I'll stick with `{@eq}` and consider writing a helper.  Thanks.
