### ISSUE TITLE
Outputing booleans only prints out trues

### ISSUE THREAD

**Issue by Ghunor** [linkedin/dustjs#764]
Given:
Template:
`<someElement value="{value1}" />
<someElement value="{value2}" />
<someElement value="{value3}" />
<someElement value="{value4}" />`
Model:
`{
  "value1": true,
  "value2": false,
  "value3": "false",
  "value4": 123
}`
Output will be:
`<someElement value="true" /><someElement value="" /><someElement value="false" /><someElement value="123" />`
I would expect:
`<someElement value="true" /><someElement value="false" /><someElement value="false" /><someElement value="123" />`

The core of the issue is that `dust.isEmpty` treats boolean false as empty.  Should change the `value === 0` into `value === 0 || value === false`

**Comment by sethkinast** [comment]
This behavior is by design. See e.g. #684

If you need to print false you can do something like `{?foo}true{:else}false{/foo}`

**Comment by Ghunor** [comment]
Thanks for the quick response.  That's an easy enough workaround.  

While not a huge deal, I question if there is a reason for this design?  While I wouldn't expect a null or NaN (falsy) to be printed from dust.reference, I feel that printing out the false is appropriate and expected.  I can't think of a scenario when a boolean reference would be used and the true would be desired while not wanting the false to print.  The only times I think anyone uses a boolean in a "reference" would be for element attributes or javascript snippets.
