### ISSUE TITLE
Render to static html

### ISSUE THREAD

**Issue by lukasoppermann** [linkedin/dustjs#768]
Hey,

I did not see any question related to this, if I missed it, please excuse me. 

Anyway, is there an easy way to render dustjs templates to static html? 
I know I can do this with gulp plugins, many are outdated and use "private" dust function.

In some situations serving a plain old html file is necessary or desired, so I feel a static html output would be very neat. Are there any plans for this? Or is this already possible?

**Comment by sethkinast** [comment]
I have #621 open tracking a tool to do this. Some of the grunt plugins should work, though.

**Comment by lukasoppermann** [comment]
Ahh, okay, so this is supposed to com in `3.0`? Is there any idea when this will happen? There is not `3.0` branch yet, correct?
